name: 🚀 Auto PR - Bump Version

on:
  push:
    branches:
      - release

jobs:
  bump-and-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - name: 🔼 Bump Patch Version
        run: npm version patch --no-git-tag-version

      - name: ✅ Commit Version Bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "chore: bump version"

      - name: 📬 Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: auto-release
          base: release
          title: "chore: automated version bump"
          body: "This PR bumps the version and prepares the package for release."
          commit-message: "chore: bump version"
